In [2]:
import numpy as np

In [20]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
x = np.array([[1,2,], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
# 入力ベクトルXに対し重み行列Wを掛ける
X = np.array([1, 2])
W = np.array([[1, 3, 5], [2, 4, 6]])
Y = np.dot(X, W)
print(Y, Y.shape)

[ 5 11 17] (3,)


## 三層ニューラルネットワーク

In [22]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
A1

(2, 3)
(2,)
(3,)


array([0.3, 0.7, 1.1])

In [23]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [28]:
# 2層目
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [29]:
# 恒等関数
def identity_function(x):
    return x

In [37]:
# 3層目
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
print(Y)
print(np.sum(Y))

[0.31682708 0.69627909]
1.0131061662729968


In [38]:
# softmax
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)   #オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [39]:
Y = softmax(A3)
print(Y)
print(np.sum(Y))

[0.40625907 0.59374093]
1.0
